### ISSUE TITLE
Protect against re-use of IP addresses when Weave network is re-created

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave-kube#10]
If you `kubectl delete` the Weave network then create a new one, it forgets everything about IP addresses it has previously allocated, thus allowing a subsequent pod to get an IP address that is in use.

We could:
- Delete the `weave` bridge when the pod is deleted.  This will have the effect of yanking the `eth0` interface from under the pods that were attached to the weave bridge.
- Scan for interfaces attached to the weave bridge and find their weave IP addresses.  In the `weave` script this is done via Docker container IDs but so far we have kept weave-kube independent of Docker.

**Comment by astraios** [comment]
Hi guys, 

I'm still running into this issue. I'm under Kubernetes 1.4.5 and I use the weave 1.8.0 daemontset.
It happens when I `kubectl delete`/`kubectl create` or some times when a container restarts.

The weave-npc container in the weave-net pod fails to restart thus the pod falls into the `CrashLoopBackOff` state.

Here is the error message I caught from the weave-npc container's log:
`ipset v6.29: Element cannot be added to the set: it's already added\n: exit status 1`

Regards,
Thomas

**Comment by awh** [comment]
Hi @notuscloud 

You're probably suffering from weaveworks/weave#2632, which is fixed in the 1.8.1 release we'll be doing later today.

**Comment by astraios** [comment]
Cool, 

Thanks
